spring:
  application:
    name: drone-service
    prefix: drn
    jpa:
      database: H2
      properties:
        hibernate:
          enable_lazy_load_no_trans: true
          dialect: org.hibernate.dialect.H2Dialect
          hbm2ddl:
            auto: update
        temp:
          use_jdbc_metadata_defaults: false
      show-sql: true
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        ddl-auto: update
      open-in-view: false
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    #    url: jdbc:h2:file:~/drone
    url: jdbc:h2:mem:drone_info
    username: sa
    password:
    driverClassName: org.h2.Driver

server:
  servlet:
    context-path: /drone-service
  port: 9090
  tomcat:
    threads:
      max: 50
      min-spare: 20
    accept-count: 300
    basedir: /
    accesslog:
      enabled: true
      directory: "/logs/drone-service"
      prefix: access_log
      buffered: false
      suffix: .log
      file-date-format: .yyyy-MM-dd
      pattern: "%h %l %u %t %r %s %b %D"

validation:
  name:
    size:
      too_long: Serial number is too large. Max 100 chars
      max-weight: Given weight exceeds 500.
      invalid-battery-per: Given battery percentage is invalid
    allowed:
      invalid-code:
      invalid-name: